import curriculum from './curriculum.json';
const catalog = [
  [
    'python',
    'Python',
    'Development',
    'Python_img.jpg',
    '12 weeks',
    'Dr. Amrita Patel',
    '4.9',
    'Start with the fundamentals. Build your confidence in Python, web development and automation.',
    'Python, Django, Flask, Pandas, REST APIs',
    'Students and graduates exploring programming',
    'Python development, backend development and automation',
  ],
  [
    'dataanalytics',
    'Data Analytics',
    'Data Science',
    'DataAnalytics_img.jpg',
    '16 weeks',
    'Rajeev Kumar',
    '4.8',
    'Turn raw data into clear insights with Excel, SQL, Python and powerful visual dashboards.',
    'Excel, SQL, Power BI, Tableau, Statistics',
    'Students, graduates and professionals interested in data',
    'Data analysis, business intelligence and reporting',
  ],
  [
    'datascience-aiml',
    'Data Science with AI & ML',
    'AI & Machine Learning',
    'Data_science.jpeg',
    '14 weeks',
    'Sneha Desai',
    '4.9',
    'Connect data science with intelligent systems, predictive models and modern AI applications.',
    'Python, TensorFlow, Keras, NLP, Machine Learning',
    'Learners exploring data science and artificial intelligence',
    'Data science, predictive analytics and AI development',
  ],
  [
    'datascience-python',
    'Data Science with Python',
    'Data Science',
    'Datascience_img.jpeg',
    '14 weeks',
    'Industry Mentors',
    '4.9',
    'Explore datasets, discover patterns and build predictive models with the Python ecosystem.',
    'Python, NumPy, Pandas, Seaborn, SQL',
    'Students, graduates and professionals interested in analytics',
    'Data science, data analysis and predictive modeling',
  ],
  [
    'aws-azure',
    'AWS Cloud Engineering & Azure AI',
    'Cloud & Security',
    'cloud.jpg',
    '10 weeks',
    'Placement Experts',
    '4.8',
    'Build a foundation in cloud infrastructure, deployment, automation and intelligent cloud services.',
    'AWS, Azure AI, Docker, Kubernetes, DevOps',
    'Learners interested in cloud platforms and AI integration',
    'Cloud engineering, cloud operations and DevOps',
  ],
  [
    'ai&ml',
    'AI & ML',
    'AI & Machine Learning',
    'AI&ml_img.jpg',
    '12 weeks',
    'AI & ML Trainers',
    '4.7',
    'Explore machine learning, neural networks and the tools behind intelligent applications.',
    'TensorFlow, Keras, OpenCV, NLP, Python',
    'Learners interested in intelligent systems and applied AI',
    'AI development, machine learning and model deployment',
  ],
  [
    'genai-agenticai',
    'Gen AI & Agentic AI',
    'AI & Machine Learning',
    'GenAI_img.jpg',
    '16 weeks',
    'TechMentors',
    '4.8',
    'Move from prompts to possibilities. Learn to build AI agents, assistants and automated workflows.',
    'LLMs, Prompt Engineering, LangChain, AI Agents',
    'Learners and professionals exploring generative AI',
    'Generative AI applications and intelligent automation',
  ],
  [
    'fullstack-aiengineer',
    'Full Stack AI Engineering',
    'Development',
    'Fullstack_Ai_img.jpg',
    '12 weeks',
    'Security Experts',
    '4.9',
    'Bring frontend, backend and AI together to create complete, intelligent web applications.',
    'React, Node.js, Python, SQL, AI APIs',
    'Learners interested in end-to-end application development',
    'Full stack development and AI application engineering',
  ],
  [
    'cybersecurity-courses',
    'Cyber Security',
    'Cloud & Security',
    'cyb.jpeg',
    '12 weeks',
    'Security Experts',
    '4.7',
    'Explore the tools and practices that help protect networks, applications and cloud environments.',
    'Cloud Security, IAM, SOC, DevSecOps, Forensics',
    'Learners interested in security and infrastructure defense',
    'Security operations, cloud security and application security',
  ],
  [
    'faculty-development-program',
    'Faculty Development Program on AI, Gen AI & Agentic AI',
    'Career & Faculty',
    'FDP.jpeg',
    '5 days · 30 hours',
    'AI Experts',
    '4.8',
    'A hands-on faculty program connecting data science, generative AI and educator portfolios.',
    'Data Engineering, ML, RAG, Agentic AI, EDA',
    'Faculty modernizing curriculum delivery and research',
    'AI teaching, curriculum development and research applications',
  ],
  [
    'campus-recruitment-training',
    'Campus Recruitment Training (CRT)',
    'Career & Faculty',
    'CRT.jpeg',
    '16 weeks',
    'AI/ML Experts',
    '4.9',
    'Prepare for recruitment with aptitude, communication, technical practice and career guidance.',
    'Aptitude, Reasoning, Communication, Interview Skills',
    'College students and graduates preparing for recruitment',
    'Preparation for campus recruitment and technical interviews',
  ],
  [
    'sap-courses',
    'SAP Courses',
    'Career & Faculty',
    'SAP.jpeg',
    '10 weeks',
    'Placement Experts',
    '4.8',
    'Explore enterprise systems with SAP tracks spanning finance, development, operations and analytics.',
    'S/4HANA, FICO, ABAP, SuccessFactors, SAP BTP',
    'Learners and professionals exploring enterprise systems',
    'SAP development, administration and functional consulting',
  ],
];
export const courses = catalog.map(
  ([
    slug,
    name,
    category,
    image,
    duration,
    mentor,
    rating,
    description,
    skills,
    audience,
    careers,
  ]) => ({
    slug,
    name,
    category,
    image,
    duration,
    mentor,
    rating,
    description,
    skills: skills.split(', '),
    audience,
    careers,
    modules: curriculum[slug as keyof typeof curriculum],
  }),
);
export type Course = (typeof courses)[number];
export const categories = [
  'All Programs',
  'AI & Machine Learning',
  'Data Science',
  'Development',
  'Cloud & Security',
  'Career & Faculty',
];
export const enrollmentUrl = 'https://proximalms.com/Home/Index';
export const email = 'registration@kalpraacademy.com';
